name: nbviewer
channels:
- javascript
dependencies:
- appnope
- coverage
- curl
- decorator
- funcsigs
- futures
- ipykernel
- ipython
- ipython_genutils
- jinja2
- jsonschema
- jupyter_client
- jupyter_core
- markdown
- markupsafe
- mistune
- mock
- nbconvert
- nbformat
- nodejs
- nose
- numpy
- notebook
- openssl
- path.py
- pbr
- pexpect
- pickleshare
- pip
- ptyprocess
- pygments
- python
- python.app
- pyzmq
- readline
- requests
- setuptools
- simplegeneric
- six
- sqlite
- terminado
- tk
- tornado
- traitlets
- wheel
- xz
- zlib
- pip:
  - elasticsearch
  - invoke
  - ipython-genutils
  - jupyter-client
  - jupyter-core
  - newrelic
  - urllib3
  - https://github.com/martinal/nbdime/archive/master.zip
